language: generic
sudo: false
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw | sed '/cask.*go.*python/d' > x.sh && source ./x.sh
  - curl -fsSkL https://raw.github.com/snogge/cask/${TRAVIS_COMMIT}/go.sh | bash
  - evm install $EVM_EMACS --use --skip
  - cask.sh
  - make start-server
env:
  - EVM_EMACS=emacs-24.3-travis
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.2-travis
  - EVM_EMACS=emacs-25.3-travis
script:
  - make test
after_failure:
  - cat test/servant/tmp/servant.log
after_script:
  - make stop-server
